services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deep_learning_from_scratch_4
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    stdin_open: true
